org: sasakiexocloud
app: exocloud-conecta-minha-saude-api
service: exocloud-conecta-minha-saude-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: us-east-2
  memorySize: 512
  timeout: 5
  logs:
    retentionInDays: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

useDotenv: true

package:
  individually: true

custom:
  logRetentionInDays: 30
  prune:
    automatic: true
    includeLayers: true
    number: 3
  dotenv:
    path: .env

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-log-retention
  - serverless-prune-versions

functions:
  createUser:
    handler: src/server.handler
    timeout: 30
    events:
      - http:
          path: /user
          method: post
          cors:
            origin: '*'
  session:
    handler: src/server.handler
    timeout: 30
    events:
      - http:
          path: /auth
          method: post
          cors:
            origin: '*'

resources:
  Resources:
    UserDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CMS-User
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: emailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    PatientDynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CMS-Patient
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: patientId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: document
            AttributeType: S
        KeySchema:
          - AttributeName: patientId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: emailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: documentIndex
            KeySchema:
              - AttributeName: document
                KeyType: HASH
            Projection:
              ProjectionType: ALL
